POST http://anicorp.tk:8599/auth
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInVzZXJuYW1lIjoibWFyaWEiLCJuYW1lIjoiTWFyaWEgSGlsbCIsImF2YXRhciI6Imh0dHBzOi8vcGJzLnR3aW1nLmNvbS9wcm9maWxlX2ltYWdlcy8xMDQ1NjgwNzY5MDQwMTAxMzc2L3Zva0VGZ1NTXzQwMHg0MDAuanBnIiwiZW1haWwiOiIiLCJpYXQiOjE2MzUwNzg1Mzl9.x-iBmcuR-H_oCdk5_agmCSu1RG9OYJDqLT6STGadXrg
############
POST http://localhost:8599/auth/login
Content-Type: application/json

{
    "username" : "phamhai",
    "password" : "abcabc"
}

############
POST http://localhost:8599/auth/register
Content-Type: application/json

{
    "username" : "maria2",
    "password" : "abcabc",
    "name" : "maria",
    "email" : ""
}


############ USER API
GET http://localhost:8599/user?_id=10
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoicGhhbWhhaSIsIm5hbWUiOiJQaOG6oW0gQ8O0bmcgSOG6o2kiLCJhdmF0YXIiOiJodHRwczovL2kuaWJiLmNvL1d2alNSalgvZDNjZTVlMzE4MzE5LmpwZyIsImVtYWlsIjoicGhhbWhhaUBnbWFpbC5jb20iLCJibHVlVGljayI6MSwiaWF0IjoxNjM3MjA3MTY5fQ.jv1LzUwteSqWPzcNTU0Als1CwBAKkBYVojyqHQhmdmk


############
GET http://localhost:8599/user/posts?_id=10
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoicGhhbWhhaSIsIm5hbWUiOiJQaOG6oW0gQ8O0bmcgSOG6o2kiLCJhdmF0YXIiOiJodHRwczovL2kuaWJiLmNvL1d2alNSalgvZDNjZTVlMzE4MzE5LmpwZyIsImVtYWlsIjoicGhhbWhhaUBnbWFpbC5jb20iLCJibHVlVGljayI6MSwiaWF0IjoxNjM3MjA3MTY5fQ.jv1LzUwteSqWPzcNTU0Als1CwBAKkBYVojyqHQhmdmk

############ POST API
GET http://localhost:8599/posts?_page=1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoicGhhbWhhaSIsIm5hbWUiOiJQaOG6oW0gQ8O0bmcgSOG6o2kiLCJhdmF0YXIiOiJodHRwczovL2kuaWJiLmNvL1d2alNSalgvZDNjZTVlMzE4MzE5LmpwZyIsImVtYWlsIjoicGhhbWhhaUBnbWFpbC5jb20iLCJibHVlVGljayI6MSwiaWF0IjoxNjM3MjA3MTY5fQ.jv1LzUwteSqWPzcNTU0Als1CwBAKkBYVojyqHQhmdmk


############ 
POST http://localhost:8599/posts/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoicGhhbWhhaSIsIm5hbWUiOiJQaOG6oW0gQ8O0bmcgSOG6o2kiLCJhdmF0YXIiOiJodHRwczovL2kuaWJiLmNvL1d2alNSalgvZDNjZTVlMzE4MzE5LmpwZyIsImVtYWlsIjoicGhhbWhhaUBnbWFpbC5jb20iLCJibHVlVGljayI6MSwiaWF0IjoxNjM3MjA3MTY5fQ.jv1LzUwteSqWPzcNTU0Als1CwBAKkBYVojyqHQhmdmk

{
    "content" : "new post",
    "imageLinks" : ""
}

#############
POST http://localhost:8599/posts/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoicGhhbWhhaSIsIm5hbWUiOiJQaOG6oW0gQ8O0bmcgSOG6o2kiLCJhdmF0YXIiOiJodHRwczovL2kuaWJiLmNvL1d2alNSalgvZDNjZTVlMzE4MzE5LmpwZyIsImVtYWlsIjoicGhhbWhhaUBnbWFpbC5jb20iLCJibHVlVGljayI6MSwiaWF0IjoxNjM3MjA3MTY5fQ.jv1LzUwteSqWPzcNTU0Als1CwBAKkBYVojyqHQhmdmk

{
    "postId": "49"
}

############# POST ############# 
GET http://localhost:8599/post/103
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoicGhhbWhhaSIsIm5hbWUiOiJQaOG6oW0gQ8O0bmcgSOG6o2kiLCJhdmF0YXIiOiJodHRwczovL2kuaWJiLmNvL1d2alNSalgvZDNjZTVlMzE4MzE5LmpwZyIsImVtYWlsIjoicGhhbWhhaUBnbWFpbC5jb20iLCJibHVlVGljayI6MSwiaWF0IjoxNjM3MjA3MTY5fQ.jv1LzUwteSqWPzcNTU0Als1CwBAKkBYVojyqHQhmdmk


#############
POST http://localhost:8599/post/103/cmt
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoicGhhbWhhaSIsIm5hbWUiOiJQaOG6oW0gQ8O0bmcgSOG6o2kiLCJhdmF0YXIiOiJodHRwczovL2kuaWJiLmNvL1d2alNSalgvZDNjZTVlMzE4MzE5LmpwZyIsImVtYWlsIjoicGhhbWhhaUBnbWFpbC5jb20iLCJibHVlVGljayI6MSwiaWF0IjoxNjM3MjA3MTY5fQ.jv1LzUwteSqWPzcNTU0Als1CwBAKkBYVojyqHQhmdmk

# {
#     "comment": "This is a comment ahihi đồ ngốc"
# }

#############
POST http://localhost:8599/post/103/react
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoicGhhbWhhaSIsIm5hbWUiOiJQaOG6oW0gQ8O0bmcgSOG6o2kiLCJhdmF0YXIiOiJodHRwczovL2kuaWJiLmNvL1d2alNSalgvZDNjZTVlMzE4MzE5LmpwZyIsImVtYWlsIjoicGhhbWhhaUBnbWFpbC5jb20iLCJibHVlVGljayI6MSwiaWF0IjoxNjM3MjA3MTY5fQ.jv1LzUwteSqWPzcNTU0Als1CwBAKkBYVojyqHQhmdmk

{
    "type": "react",
    "action": "like"
}

################################################################
GET http://anicorp.tk:8599/user?_id=2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoicGhhbWhhaSIsIm5hbWUiOiJQaOG6oW0gQ8O0bmcgSOG6o2kiLCJhdmF0YXIiOiJodHRwczovL2kuaWJiLmNvL1d2alNSalgvZDNjZTVlMzE4MzE5LmpwZyIsImVtYWlsIjoicGhhbWhhaUBnbWFpbC5jb20iLCJibHVlVGljayI6MSwiaWF0IjoxNjM3MjA3MTY5fQ.jv1LzUwteSqWPzcNTU0Als1CwBAKkBYVojyqHQhmdmk
